# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

workflows:
  check_and_coverage:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1g
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "buildSrc/build.gradle" }}-{{ checksum "sundries/build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "buildSrc/build.gradle" }}-{{ checksum "sundries/build.gradle" }}

      - run:
          gradle check jacocoTestReport
      - codecov/upload:
          file: sundries/build/reports/jacoco/test/jacocoTestReport.xml

